ember-cli-code-coverage/ember-cli-code-coverage

README.md, index.js, lib/babel-istanbul-instrumenter.js, lib/config.js, lib/coverage-instrumenter.js
This reverts commit d51c6702c208334046ad7a712cabb173f26c309a and resolves #12.
This change uses the applications babel configuration for the instrumenter's configuration.
=> Report Correct Line Numbers for esnext

config/release.js, package.json
Will now automatically publish to `npm`.
=> Update ember-cli-release to allow easier releasing.

lib/coverage-instrumenter.js
=> Add `includePolyfill` to removed babel options.

index.js, lib/coverage-instrumenter.js, test/unit/index-test.js
=> Processed addon js files

index.js
This log message is pretty noisy.
=> Remove stray console.log

.travis.yml, index.js, lib/templates/test-body-footer.html, test/unit/index-test.js
- Solution is thanks to @wagenet
- Change node versions to test against
Should fix #20
=> Factor in unused/unrequired files in to coverage %

lib/templates/test-body-footer.html
Fixes the hanging issue of #88
Also changed `onload` to `onreadystatechange`.
`onload` doesn't trigger on chromium.
=> Fixes the hanging issue of #88

index.js, test/fixtures/my-addon/addon-test-support/uncovered-test-support.js, test/fixtures/my-app-with-in-repo-addon/lib/my-in-repo-addon/addon-test-support/uncovered-test-support.js, test/integration/in-repo-addon-coverage-test.js, test/unit/index-test.js
=> Support for addon-test-support

index.js
Fixes https://github.com/kategengler/ember-cli-code-coverage/issues/181
=> Fix fileLookup is null in testemMiddleware

package.json, test/integration/in-repo-addon-coverage-test.js, test/integration/in-repo-engine-coverage-test.js
=> Remove `co` usage

index.js, package.json, yarn.lock
Use native array spread operator instead.
=> Remove lodash.concat dependency

index.js, lib/attach-middleware.js, lib/coverage-merge.js, test/unit/index-test.js
see https://eslint.org/docs/rules/object-shorthand
=> Use shorthand methods and named functions

test/helpers/in-repo-addon.js, test/helpers/in-repo-engine.js, test/integration/app-coverage-test.js
... to make those Promise chains more readable
=> tests: Use async/await

lib/attach-middleware.js, lib/coverage-merge.js
This makes the code a little easier to understand... 😉
=> Use `.includes()` instead of `.indexOf()`

.github/workflows/ci.yml, .github/workflows/release.yml, package.json, packages/ember-cli-code-coverage/package.json
Bumps node from 10 to 12 via volta
=> Use volta-cli for node and yarn versioning

package.json, test-packages/my-app-with-custom-path-in-repo-addon/package.json, test-packages/my-app-with-in-repo-addon/package.json, test-packages/my-app-with-in-repo-engine/package.json, test-packages/my-app/package.json
=> Fix correct version for test packages

README.md, packages/ember-cli-code-coverage/addon-test-support/index.js, packages/ember-cli-code-coverage/index.js, yarn.lock
Allow apps to override the namespace map and which modules get forceLoaded via customization options.
=> Add advanced customizations for namespace discovery and module loading

.github/workflows/release.yml
May fix CI publishing
- bump to latest checkout action
=> Add registry-url to volta action

README.md
Fixes https://github.com/kategengler/ember-cli-code-coverage/issues/347
=> Add documentation for setup in standalone addons

packages/ember-cli-code-coverage/index.js
=> Fix serverMiddleware for development mode

package.json, packages/ember-cli-code-coverage/package.json, packages/ember-cli-code-coverage/pnpm-lock.yaml, pnpm-lock.yaml
=> Bump some deps
