lib/config.js
Without this change, it is not possible to customize any of the default values (because any customizations are clobbered by the default config).
=> Allow users config to override the default config.

lib/templates/test-body-footer.html
Works the same:
And doesn't troll apps running without jQuery (don't ask yet if that is
a thing plz :wink: ).
=> Avoid requiring jQuery for sending the coverage report back.

lib/templates/test-body-footer.html
In trying to diagnose why tests hang when trying to report coverage with PhantomJS, I realized `this.response` was coming back as a string rather than a parsed object after posting the coverage information.
It turns out (as far as I can tell), Phantom just doesn't honor `xhr.responseType = 'json'`, and if you read it back, you just get `''`. To convince myself I wasn't going crazy, I captured result of loading [this page](https://mathiasbynens.be/demo/json-responsetype) in Phantom 2.1, and it looks like this:
Adding an explicit `JSON.parse` avoids the early return so that the Testem callback gets invoked and everything cleans up correctly.
I'm not sure how (or whether) to test this; any input on that is welcome. Thanks!
=> Fix hang when running in PhantomJS.

index.js, test/unit/index-test.js
This should fix #45, where addons whose name is different from the one in their `package.json` don't get coverage.
=> Handle addons with different package names

index.js
Let the underlying subsystem deal with the `path.sep` differences, the logic here was incorrectly interchanging `\` and `/` on windows.
Fixes #48.
=> Use posix paths for dealing with modules.

index.js, test/unit/index-test.js
this.parent.name is a function (if defined), this.parent.pkg.name is the expected name of the package.
Using 0.3.3 I get no coverage for any files in the app. (worked in 0.3.2)
=> return actual name not function from _parentName

index.js
Renamed `_doesFileExistIsCurrentProjectAddonModule` to
`_doesFileExistInCurrentProjectAddonModule` and its parameter from
`_relativePath` to `relativePath` to make is consistent with other
`_doesFileExist...`-functions. Cosmetics only, no functional changes.
=> Cosmetics for docs, renamed function name and parameter name

README.md
The README references the need to create a pass through when using both Mirage and Pretender, but only supplies an example for Mirage. I had to figure out what was needed for Pretender and don't want the next person in the same position to have to do the same.
=> Update README.md with Pretender example.

.eslintrc.js, README.md, lib/attach-middleware.js, lib/config.js, package.json
This allows passing `addonName` in the config and it will replace `modules/my-addon` with `addon` in the lcov.info file. This should allow proper file mapping for things like Code Climate and Coveralls. Does this approach look okay to you @rwjblue and @kategengler?
Resolves #36
=> Add ability to pass addonName and fix paths

.travis.yml, lib/templates/test-body-footer.html, package.json, tests/unit/handle-modules-throwing-on-import-test.js
To ensure coverage percentages are accurate we added some code to automatically require all modules in the application/addon.  If an error was detected while loading the module we annotated it with information on why it occurred, but still rethrew the error. 
In retrospect, it seems that a number of applications have dormant (and invalid) modules that exist in the app (at least during tests).  Our prior concept/assertion that rethrowing an error was the correct path turns out to itself be painful.
This changes that error into a warning (because I truly believe we should encourage folks to fix these scenarios).
Fixes https://github.com/kategengler/ember-cli-code-coverage/issues/63.
=> Avoid throwing errors while requiring files for coverage.

index.js, lib/attach-middleware.js, lib/config.js, lib/coverage-instrumenter.js, package.json
Moved from attach-middleware to coverage-instrumenter, where the other path fixing occurs. Resolves #67
=> Refactor add-on renaming

lib/attach-middleware.js
@rwjblue had a magical suggestion of setting `sync` to `true`, as he thought perhaps express was timing out here, and it seems to have done the trick.
This change gets nested coverage html files generated. Some were being skipped without this.
=> Set sync to true, to make nested files work

.travis.yml
This should hopefully stop us from having multiple PR builds, and should use the Chrome available already on Travis, rather than installing it again.
=> Restrict branches for builds, use preinstalled Chrome

lib/templates/test-body-footer.html
I experienced a difficult to reproduce edge case on an Ember application with > 500 tests:
When running with coverage on the v0.3.8 tag, my test server crashes right after the tests complete with the following error:
```
Error: request aborted
at IncomingMessage.onAborted ([snip]/ember-cli-code-coverage/node_modules/raw-body/index.js:269:10)
at emitNone (events.js:86:13)
at IncomingMessage.emit (events.js:185:7)
at abortIncoming (_http_server.js:283:11)
at Socket.serverSocketCloseListener (_http_server.js:296:5)
at emitOne (events.js:101:20)
at Socket.emit (events.js:188:7)
at TCP._handle.close [as _onclose] (net.js:498:12)
```
This wasn't happening on the version we were using before (v0.2.2), so I figured it was a change in the recent minor bumps that caused the breakage. I bisected …
=> Fix phantomjs `request aborted` edge case

lib/templates/test-body-footer.html
The onload event for XHRs does not fire when the XHR is synchronous.
This was causing the callback to never be called and the test suite
to hang indefinitely.
See https://github.com/kategengler/ember-cli-code-coverage/pull/82 for the discussion that led up to this.
=> Use synchronous control flow when making synchronous requests

README.md, index.js, lib/attach-middleware.js, lib/coverage-merge.js, package.json
Allows use of parallel testing with ember-exam or similar.
Additional configuration flag `parallel`, when set to true will output coverage into multiple directories, with a random suffix. The `coverage-merge` command can then be used after the build to merge them together.
=> Add coverage-merge command and parallel configuration

package.json
In `npm: 2.14.9`, my app wasn't pulling in the `rsvp` module defined under `ember-cli-code-coverage`'s `devDependencies`.
To fix this, I've moved `rsvp` into `dependencies` as its now required as part of the `lib/coverage-merge`.
This should help address https://github.com/kategengler/ember-cli-code-coverage/issues/88#issuecomment-270784595
=> Move `rsvp` package to `dependencies`

README.md, index.js, lib/attach-middleware.js, lib/config.js, lib/coverage-merge.js, test/integration/coverage-test.js, test/unit/index-test.js, tests/dummy/config/coverage-parallel.js
On this PR I'm trying to tackle the issue brought up in #42 by using `configPath` instead of the hard coded config path value. 
According to the [ember-cli docs](https://ember-cli.com/api/classes/Project.html#method_configPath) `configPath` is private but I couldn't figure out a better/public way to determine this value. If anybody knows of a better way to make this change I'll be happy to integrate the feedback.
=> Fixes #42 use configPath instead of hard-coded config

lib/coverage-instrumenter.js
This messaging was confusing to me so I took a stab at clarifying the intent.
Fixes #106 and #108
=> Improve ES7 error message

README.md
It might be helpful to suggest how/where to run `coverage-merge` for people looking to set this up in a CI environment.
The only other thing I might add is that you need to run `npm test` and have the appropriate configuration there for `posttest` to trigger, but I'm not sure if that's overkill since that should be common knowledge.
=> Suggest using `posttest` hook for `ember coverage-merge`

lib/coverage-instrumenter.js
Starting in (I believe) ember-cli@2.12, addon files stopped being nested under `modules/`, which means the path correction logic here wasn't working properly for them.
If you have thoughts on the best way to test this change, I'd welcome them 🙂
=> Resolve addon file paths correctly in CLI >= 2.12

package.json, yarn.lock
The previously locked version was not compatible with `node@8` (due to `engines` shenanigans).
=> Update minimum version of ember-cli-babel.

index.js, test/unit/index-test.js
In combination with typed-ember/ember-cli-typescript#144, this should enable coverage reporting for TypeScript files. (Previously we were checking this addon's _own_ preprocessor registry, which would never contain any additional extensions)
=> Use the parent registry for determining JS extensions

package.json, yarn.lock
istanbul-api@2.0.1 was released on June 6, 2018 and tagged as "next" on npm. The breaking change is pretty minor: https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-api/CHANGELOG.md#breaking-changes
The feature I need in 2.x comes from the istanbul-reports dependency ([CHANGELOG](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/CHANGELOG.md#140-2018-04-17)), which provides the ability to load custom reporters. (We use bitbucket, which has a [custom report format](https://bitbucket.org/atlassian/bitbucket-code-coverage/src/5738efe5414e6bee6fb31db9fb93dfb0afbd6bb0/code-coverage-plugin/)).
=> upgrade istanbul-api to 2.0.1

index.js
`ember-cli@^3.2.0` includes https://github.com/ember-cli/ember-cli/pull/7857, which filters out [blacklisted](https://ember-cli.com/managing-dependencies#whitelisting-and-blacklisting-assets) addons. Therefore, when an in-repo addon is blacklisted, even though its path is listed in package.json, `project.findAddonByName()` will not find it. This results in an error when running `COVERAGE=true ember test` because `ember-cli-code-coverage` assumes all in-repo addons listed in the host app's package.json will be found. This PR adds a truthy filter to remove not-found in-repo addons.
=> Filter out in-repo addons that could not be found

lib/attach-middleware.js, test/integration/app-coverage-test.js
Updated `app-coverage-test.js` to test with babel 7 (in-repo-addon and in-repo-engine tests still use babel 6)
fixes #189
=> fix: handle babel 7 absolute paths

test/integration/app-coverage-test.js
I noticed that the first npm install that ember-addon-tests was doing was messing up the node_modules directory since [build #433](https://travis-ci.org/kategengler/ember-cli-code-coverage/jobs/449549515), not sure why (the npm version hadn't changed) - I can only assume that, since we're not using a lockfile, one of the downstream dependencies changed and caused an issue. Am hoping that this should resolve it, but without knowing the root cause I can't be sure (should speed up the build a little at least)
=> fix build issues

index.js, test/unit/index-test.js
Invoking covered module name instead of the covered addon's project payload whenever assessing covered addon's name.
When referencing a covered addon, we should ideally use the module to get the module name, as this is the source of truth when designating the addon name. This fixes the issue wherein if there exists any discrepancy between the module and project name, the coverage report ends up being inaccurate.
Fixes #235
=> Ensure coverage collection accounts for addons with a custom `moduleName` implementation

index.js
Attempt to fix https://github.com/kategengler/ember-cli-code-coverage/issues/232.
See a detailed description and analysis of the issue in #232.
The idea is to default `fileLookup` to `{}` instead of `null` this way regardless of the fact that `included` will run or not `fileLookup` should always be non-null.
I'm not 100% sure if this is the best fix for this issue. The issue may be elsewhere in the addons system. I'll leave the reviewer(s) weigh in on this.
=> Default fileLookup to {} instead of null.

lib/attach-middleware.js, lib/templates/test-body-footer.html
fix `InvalidStateError` exception
This commit fixes #244.
The xhr.responseText property cannot be accessed unless xhr.responseType is either 'text' or '',
otherwise it throws an error:
Uncaught InvalidStateError: Failed to read the 'responseText' property from 'XMLHttpRequest':
The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json')
This will therefore happen in handleCoverageResponse whenever
a request returns falsy. This should never happen, but is occasionally
flaking and producing the above error.
This commit fixes a few likely culprits:
- responseType = `json` was being set after `xhr.send`, which may cause a race condition
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/response
- the middleware called res.send with a CoverageMap may …
=> fix `InvalidStateError` exception

index.js
Fixes #210 
This PR addresses the issue:
`TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at writeCoverage (/.../node_modules/ember-cli-code-coverage/lib/attach-middleware.js:29:10)`
This issue arises when --path option is specified in the command such as `COVERAGE=true ember exam --path='./testOutput' --split=20 --parallel=1`.
This is due to the included hook which is not invoked when --path option is passed.
We are calling the included hook if the fileLookup object is not built. By doing this, we can build the object correctly which in turn will rectify the error.
=> test cases fail with --path option in 1.0.0-beta.8 version

CHANGELOG.md, RELEASE.md, package.json, yarn.lock
Largely the result of running `npx create-rwjblue-release-it-setup`, also removed `changelog` script and `lerna-changelog` dependency.
=> Update release process

package.json, yarn.lock
This was originally added in #115 but #141 fundamentally changed the implementation such that it was not needed.
=> Remove unused babel-plugin-transform-async-to-generator package

lib/coverage-merge.js, package.json, test/integration/app-coverage-test.js, test/integration/app-coverage-typescript-test.js, test/integration/in-repo-addon-coverage-test.js, test/integration/in-repo-engine-coverage-test.js, yarn.lock
Now that we rely on more recent Node versions, we no longer need to use RSVP for promisy things.
=> Remove RSVP dependency.

index.js
The code in `requireBabelPlugin` was attempting to ensure that the cache key used by broccoli-babel-transpiler incorporated the `babel-plugin-istanbul` directory (so that the cache would be invalidated if it was modified / reinstalled).
At the time, this was the best we could do, but broccoli-babel-transpiler now properly caches plugins when provided an absolute path (which is what `require.resolve` returns). This _also_ means that consumers using ember-cli-code-coverage will now be able to have Babel parralellization (which is not possible with the prior implementation).
=> Ensure coverage build is parallelizable

lib/config.js, package.json, yarn.lock
`extend` (when not using the `deep` option) is doing the same shallow merge that `Object.assign` does. Since we weren't using the `deep` argument (first argument would have to be boolean for that behavior), we can replace this usage with `Object.assign`.
=> Replace `extend` package with `Object.assign`

lib/templates/test-body-footer.html, test/unit/index-test.js
Unfortunately, this codepath is not under test and the changes from https://github.com/kategengler/ember-cli-code-coverage/pull/251 left it in an invalid state.
* The REQUEST_ASYNC variable was no longer present, and therefore referencing it threw an error
* The guard around `xhr.responseText` was no longer needed (we only ever get `JSON`, and `xhr.response` is already parsed properly for us)
We ultimately need to refactor to get this coverage reporting under test (plausibly an end-to-end acceptance test that confirms the expected JSON reporter output after running all the tests).
=> Fix issue with coverage report.

README.md
Versions <1.0.0-beta.9 in fact do not provide TS coverage support.
=> Update instructions for Typescript integration to use 1.0.0-beta.9

.babelrc, package.json, yarn.lock
There does not appear to be any reason for us to use the Babel transpilation and polyfill, so this PR gets rid of them.
=> mocha: Remove unnecessary Babel integration

index.js, test/unit/index-test.js
This method appears to only be used by the tests that test it 🤔
=> Remove unused `_parentName()` method

index.js, test/integration/app-coverage-test.js, test/integration/in-repo-addon-coverage-test.js, test/integration/in-repo-engine-coverage-test.js, test/unit/index-test.js
Environment variables are inherently string-based and can't use boolean values. This commit changes `_isCoverageEnabled()` to only accept the `true` string (case insensitive).
This probably does not need to be considered a breaking change, since from the outside only the string value was available anyway.
=> Simplify `_isCoverageEnabled()` method

lib/attach-middleware.js, lib/coverage-merge.js, package.json, yarn.lock
`istanbul-api` was deprecated in favor of using the individual `instanbul-*` libraries migrated to here.
---
Because we don't currently support running code coverage against a dummy app's code, and this addon doesn't have any code in addon/addon-test-support/app I can't actually verify if this is working very easily.
The things that I would like verified are:
* `COVERAGE=true ember test` emits a valid coverage file, and the reports look correct
* the coverage merge functionality still works properly (and can emit a valid final report)
=> Remove deprecated istanbul-api package.

package.json, test-packages/__snapshots__/custom-path-in-repo-addon-test.js.snap, test-packages/__snapshots__/in-repo-addon-test.js.snap, test-packages/__snapshots__/in-repo-engine-test.js.snap, test-packages/__snapshots__/my-app-test.js.snap, test-packages/custom-path-in-repo-addon-test.js, test-packages/in-repo-addon-test.js, test-packages/in-repo-engine-test.js, test-packages/index-test.js, test-packages/my-app-test.js, yarn.lock
... instead of Mocha and Chai. And this introduces snapshot tests to assert on the `coverage-summary.json` results.
=> Use Jest for testing

packages/ember-cli-code-coverage/index.js, test-packages/__snapshots__/my-app-test.js.snap, test-packages/index-test.js, test-packages/my-app-test.js
At the company where I work I was working on speeding up tests by splitting them and running them in parallel. For this I used the `--path` option, after which the coverage wasn't working anymore. I saw [this](https://github.com/kategengler/ember-cli-code-coverage/issues/271) issue, which is the exact problem I ran into. However, the initial fix mentioned there wasn't actually working, so the issue is still there in v1.0.0. Reason is that `!this.fileLookup` returns false for empty objects. After fixing that line, the coverage was working again.
I also added a basic test to make sure it actually works.
=> Fix empty reports when path option to existing build is used

packages/ember-cli-code-coverage/index.js, test-packages/__snapshots__/in-repo-addon-test.js.snap, test-packages/index-test.js, test-packages/my-app-with-in-repo-addon/app/services/my-service.js, test-packages/my-app-with-in-repo-addon/lib/my-in-repo-addon/addon/services/my-service.js, test-packages/my-app-with-in-repo-addon/lib/my-in-repo-addon/app/services/my-service.js, test-packages/my-app-with-in-repo-addon/tests/unit/services/my-service-test.js
Given a repo with an in-repo-addon that re-exports a module, e.g. service, when the repo has an overriding file of what the in-repo-addon exports, then the overriding file should be included in the lcov file.
E.g., Given the following paths exists in the app
```
app/services/my-service.js
lib/my-in-repo-addon/addon/services/my-service.js
lib/my-in-repo-addon/app/services/my-service.js
```
Expected: lcov file should include the following lines.
```
SF:app/services/my-service.js
SF:lib/my-in-repo-addon/addon/services/my-service.js
```
Actual: lcov file includes the wrong path, such as the following lines.
```
SF:lib/my-in-repo-addon/app/services/my-service.js
SF:lib/my-in-repo-addon/addon/services/my-service.js
```
=> Fix missing/incorrect file paths in lcov

packages/ember-cli-code-coverage/lib/templates/test-body-footer.html
Reason:
on testem, callback will invoke afterTests and it will emit disconnect. There are rare occasions empty data gets into handleCoverageResponse.
Which skips emitting disconnect event and hence testem will invoke processExit and it will eventually time outs no matter what timeout value is.
Invoking callback regardless of data's value will make sure testem to invoke afterTests
cc @rwjblue
=> Make sure to fire callback whenever handleCoverageResponse has fired

README.md, packages/ember-cli-code-coverage/index.js, packages/ember-cli-code-coverage/lib/attach-middleware.js
Allow customizing how the file path adjustment works by passing a function as an option. Removing the namespace mapping override as its not really needed with the customAdjustment function.
=> Adding `modifyAssetLocation` config option

README.md, test-packages/__snapshots__/in-repo-addon-test.js.snap, test-packages/my-app-with-in-repo-addon/ember-cli-build.js, test-packages/my-app-with-in-repo-addon/lib/my-in-repo-addon/app/utils/my-in-repo-addon-app-covered-util.js, test-packages/my-app-with-in-repo-addon/tests/unit/utils/my-in-repo-addon-app-covered-util-test.js
This PR adds a test to confirm `modifyAssetLocation` works as expected when not using the `--path` option. I cherry-picked this from https://github.com/kategengler/ember-cli-code-coverage/pull/342 and used `modifyAssetLocation` to make the tests pass. The example in the readme wasn't sufficient though, as the `relativePath` doesn't start with `app`, but with the project name (as this is not replaced by the `namespaceMapping` yet at this point), so I adjusted the readme to make this more clear.
=> Add test for files in app directory of in-repo addons

packages/ember-cli-code-coverage/index.js
If an addon overrides `moduleName` to be different from `name`, the code coverage would be all 0. This PR changes `item.name` to `item.moduleName()`. `moduleName` returns `name` by default so this should cover both cases.
=> use `moduleName` instead of `name` when building namespace mappings

packages/ember-cli-code-coverage/lib/attach-middleware.js
We have a mono repo with v2-style in-repo addons and tests. For instance, we have `ROOT/addons/internal` and `ROOT/tests/internal`. The path relative to our tests end up looking like `../../addons/internal`. Without the new conditional, we'd end up hitting the fallback case which tries to make everything relative to `tests/internal/app` this would end up getting translated into `ROOT/tests/addons/internal` which is _not_ the correct path. I believe it should always be correct to pass relative paths through as-is, which is what I've done here. This solves the problem for our uses.
=> Handle relative paths when fixing keys

README.md, packages/ember-cli-code-coverage/lib/attach-middleware.js, packages/ember-cli-code-coverage/lib/coverage-merge.js, packages/ember-cli-code-coverage/lib/reports.js, test-packages/reports-test.mjs, test-packages/utils.mjs
I'm using codeclimate for my OSS projects. And for that to work, the code-coverage must be relative to repo-root, instead of project-root. This was easy done with the `vitest` project in there as it allowed to configure reports: https://vitest.dev/guide/reporters.html (it's also the same syntax that eslint uses to configure your rules).
In `ember-cli-code-coverage`, the config is always `{}` or "no config allowed". Now this PR adds support for the same config, that `vitest` allows.
I'm already using this with a patch on my OSS projects, here is one such [PR pointed to the config](https://github.com/hokulea/aria-voyager/pull/8/files#diff-1eac964ac8ee654baaf6c1c509383e0400a49292fda5a7b13e59249939159014).
It works, I can see my coverage on codeclimate and this PR brings back this support to …
=> Add Config per Reporter
